BEGIN;

ALTER TABLE rollup_shadow_submissions
    ADD COLUMN IF NOT EXISTS record_tx_hash VARCHAR(66) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS accept_tx_hash VARCHAR(66) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS record_submitted_at BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS accept_submitted_at BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS accepted_at BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_error TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS last_error_at BIGINT NOT NULL DEFAULT 0;

COMMIT;
